on:
  push:
    branches:
      - 'test-workflow'
jobs:
  create-main-branch:
    name: Create main branch in target repo
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout master with all history on the target repo
        uses: actions/checkout@master
        with:
          repository: mdeggies/github-private-actions
          token: ${{ secrets.GH_TOKEN }}
          # Number of commits to fetch. 0 indicates all history.
          fetch-depth: 0
          ref: 'master'
      - name: Create the main branch
        run: |
          git branch -m master main
      - name: Push main branch
        run: |
          git push -u origin main
  update-default-branch:
    name: Update the default branch to main
    runs-on: ubuntu-18.04
    steps:
      - uses: octokit/request-action@v2.x
        id: update_default_branch
        with:
          route: PATCH /repos/:owner/:repo
          repository: mdeggies/github-private-actions
          default_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: "echo status: ${{ steps.update_default_branch.outputs.data }}"
        