on:
  push:
    branches:
      - 'test-workflow'
jobs:
  check-for-main:
    name: Check to see if main branch already exists
    runs-on: ubuntu-18.04
    steps:
      - name: Check to see if main branch exists
        uses: octokit/request-action@v2.x
        id: check_for_main
        with:
          # https://developer.github.com/v3/repos/branches/#get-a-branch
          route: GET /repos/:owner/:repo/branches/:branch
          owner: mdeggies
          repo: github-private-actions
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 
      - name: Check if main == master
        if: ${{ success() }}
        run: |
          git checkout main
          if ! git diff-index --quiet master;
          then
            echo "Main isn't equal to master.."
            # Send slack alert -- main already exists but != master, so manually check it out
            # Or simply overwrite main? 
            exit 1
          fi
  create-main-branch:
    if: ${{ success() }}
    name: Create main branch in target repo
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout master with all history on the target repo
        uses: actions/checkout@master
        with:
          repository: mdeggies/github-private-actions
          token: ${{ secrets.GH_TOKEN }}
          # Number of commits to fetch. 0 indicates all history.
          fetch-depth: 0
          ref: 'master'
      - name: Create the main branch
        run: |
          git branch -m master main
      - name: Push main branch
        run: |
          git push -u origin main
  update-default-branch:
    needs: create-main-branch
    name: Update the default branch to main
    runs-on: ubuntu-18.04
    steps:
      - name: Update the default branch to main
        uses: octokit/request-action@v2.x
        id: update_default_branch
        with:
          route: PATCH /repos/:owner/:repo
          owner: mdeggies
          repo: github-private-actions
          default_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  update-pr-target:
    needs: update-default-branch
    name: Update the base branch for all open PR's
    runs-on: ubuntu-18.04
    steps:
      - name: Get a list of all open PR's
        uses: octokit/request-action@v2.x
        id: get_open_prs
        with:
          # https://developer.github.com/v3/pulls/#list-pull-requests
          route: GET /repos/:owner/:repo/pulls
          owner: mdeggies
          repo: github-private-actions
          state: open
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: |
          "echo list of open PR's: ${{ fromJson(steps.get_open_prs.outputs.data).number }}"
          echo ::set-env name=OPEN_PRS::$(echo ${{ fromJson(steps.get_open_prs.outputs.data).number }})
      # - name: Checkout current repo
      #   uses: actions/checkout@test-workflow
      - name: See if we can list the PR's from the previous job
        run: |
          ./scripts/list_open_prs.sh