on:
  push:
    branches:
      - '*/*'
jobs:
  get-branch-name:
    name: Get current branch name
    runs-on: ubuntu-18.04
    outputs:
      branch: ${{ steps.current_branch.outputs.branch }}
      owner: ${{ steps.current_branch_owner.outputs.owner }}
      repo: ${{ steps.current_branch_repo.outputs.repo }}
    steps:
    - id: current_branch
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
    - id: current_branch_owner
      run: echo "##[set-output name=owner;]$(echo ${{ steps.current_branch.outputs.branch }} | awk -F "/" 'NR==1 {print $1}')"
    - id: current_branch_repo
      run: echo "##[set-output name=repo;]$(echo ${{ steps.current_branch.outputs.branch }} | awk -F "/" 'NR==1 {print $2}')"
  check-for-main:
    name: Check if main branch exists
    runs-on: ubuntu-18.04
    needs: get-branch-name
    steps:
      # - run: ${{ needs.get-branch-name.outputs.repo }}
      - name: Check if main branch exists
        uses: octokit/request-action@v2.x
        id: check_for_main
        with:
          # https://developer.github.com/v3/repos/branches/#get-a-branch
          route: GET /repos/:owner/:repo/branches/:branch
          owner: ${{ needs.get-branch-name.outputs.owner }}
          repo: ${{ needs.get-branch-name.outputs.repo }}
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 
      - name: Checkout main branch if it exists
        if: ${{ success() }}
        uses: actions/checkout@v2
        with:
          repository: ${{ needs.get-branch-name.outputs.branch }}
          token: ${{ secrets.GH_TOKEN }}
          # Number of commits to fetch. 0 indicates all history.
          fetch-depth: 0
          ref: 'main'
      - name: Check if main == master
        if: ${{ success() }}
        run: |
          if ! git diff-index --quiet origin/master;
          then
            echo "Main isn't equal to master.."
            # Send slack alert -- main already exists but != master, so manually check it out
            # Or simply overwrite main? 
            exit 1
          else
            echo "Main exists and is equal to master.. skip create-main-branch job"
          fi
  create-main-branch:
    if: ${{fromJson(needs.check-for-main.outputs.status)}} != 200
    name: Create main branch in target repo
    runs-on: ubuntu-18.04
    needs: [check-for-main, get-branch-name]
    steps:
      - name: Checkout master with all history on the target repo
        uses: actions/checkout@v2
        with:
          repository: ${{ needs.get-branch-name.outputs.branch }}
          token: ${{ secrets.GH_TOKEN }}
          # Number of commits to fetch. 0 indicates all history.
          fetch-depth: 0
          ref: 'master'
      - name: Create main branch
        run: git branch -m master main
      - name: Push main branch
        run: git push -u origin main
  update-default-branch:
    name: Update default branch to main
    runs-on: ubuntu-18.04
    needs: get-branch-name
    steps:
      - name: Update the default branch to main
        uses: octokit/request-action@v2.x
        id: update_default_branch
        with:
          route: PATCH /repos/:owner/:repo
          owner: ${{ needs.get-branch-name.outputs.owner }}
          repo: ${{ needs.get-branch-name.outputs.repo }}
          default_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  update-pr-target:
    name: Update the base branch for all open PR's
    runs-on: ubuntu-18.04
    needs: [get-branch-name, update-default-branch]
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install requests PyGithub
      - name: Update target branch of open PR's from 'master' to 'main'
        run: python ./scripts/update_pr_target_branch.py ${{ secrets.GH_TOKEN }} ${{ needs.get-branch-name.outputs.owner }} ${{ needs.get-branch-name.outputs.repo }}
